#!/bin/bash

source /usr/local/bin/tomatocam.ini
DATE=`date +%FT%T`

## -t -- Timeout for taking a picture
## -w -- width set to 256 for small data size
## -h -- height set to 256 for small data size
## -q -- quality <0 - 100>  set to 50 for small data size
## -n -- no preview, easier on the processor.
## Cheap and easy setting
raspistill -vf -hf -ex auto -awb auto -t 1 -n -w 512 -h 512 -q 75 -o ${PIXDIR}/${DATE}pict.jpg
cp ${PIXDIR}/${DATE}pict.jpg ${PIXDIR}/last.jpg
