#!/bin/bash

source /usr/local/bin/tomatocam.ini

COUNT=1
for FILE in ${DIR}/*
do
    ln -s ${FILE} ${MOVIEDIR}/image-${COUNT}.jpg
    COUNT=$((COUNT+1))
done

avconv -y -i "${MOVIEDIR}/image-%d.jpg" -r 20 ${MOVIEDIR}/output.mp4 > /dev/null 2>&1

rm ${MOVIEDIR}/*.jpg
