#!/bin/bash
set -x
source /usr/local/bin/tomatocam.ini

## Make links from the pix dir called image-%d.jpg
COUNT=1
for FILE in ${PIXDIR}/*
do
    ln -s ${FILE} ${MOVIEDIR}/image-${COUNT}.jpg
    COUNT=$((COUNT+1))
done

avconv -y -i "${MOVIEDIR}/image-%d.jpg" -vf gradfun,hqdn3d -r 10 ${MOVIEDIR}/output.mp4 > /dev/null 2>&1
# avconv -y -i "${MOVIEDIR}/image-%d.jpg" -r 10 /var/www/html/output.mp4 > /dev/null 2>&1
# Think about using concatenation.

mv -fu ${MOVIEDIR}/output.mp4 /var/www/html/output.mp4
rm ${MOVIEDIR}/*.jpg
